---
title: "IDS575_Final_Project"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Library Import
```{r}
library(tidyverse)
library(lubridate)
library(rpart)
library(gbm) 
library(glmnet)
library(ranger)
library(matrixStats)
library(caret)

```

## Data Import
```{r}
train_data <- read.csv("~/School/IDS575 Machine Learning/Project/train.csv", header=TRUE, stringsAsFactors = FALSE)
test_data <- read.csv("~/School/IDS575 Machine Learning/Project/test.csv", header=TRUE)
india_data_1 <- read.csv("~/School/IDS575 Machine Learning/Project/India_test.csv", header=TRUE, stringsAsFactors = TRUE)
india_data_2 <- read.csv("~/School/IDS575 Machine Learning/Project/India_train.csv", header=TRUE, stringsAsFactors = TRUE)
king_county_data <- read.csv("~/School/IDS575 Machine Learning/Project/kc_house_data.csv", header=TRUE, stringsAsFactors = TRUE)
sydney_data <- read.csv("~/School/IDS575 Machine Learning/Project/Sydney_output.csv", header=TRUE, stringsAsFactors = TRUE)
```

## Data Import
```{r}
# Remove variables which have more than 60% missing values
train_data <- train_data %>% select(-names(train_data)[colMeans(is.na(train_data))>0.6])

# Dealing with missing values
train_data <- train_data %>% replace_na(list(LotFrontage=0, 
                                             MasVnrType=0,
                                             MasVnrArea=0, 
                                             BsmtQual=0, 
                                             BsmtCond=0, 
                                             BsmtExposure=0,  
                                             BsmtFinType1=0, 
                                             BsmtFinType2=0, 
                                             Electrical=0, 
                                             FireplaceQu=0, 
                                             GarageType=0, 
                                             GarageYrBlt=0, 
                                             GarageFinish=0, 
                                             GarageQual=0, 
                                             GarageCond=0))

# Convert variables to  a factor variable
#for
#train_data$MSZoning <- factor(train_data$MSZoning)
for(i in 1:ncol(train_data)){
  if(sapply(train_data[1,i], class) == "character"){
    train_data[,i] <- as.factor(train_data[,i])
  }
}
#train_data <- as.data.frame(unclass(train_data))

#sapply(train_data[1,3], class) == "character"
head(train_data)
```




# Data Exploration
```{r}

plot(sqrt(train_data$LotArea), train_data$SalePrice)
plot(sqrt(train_data$GrLivArea), train_data$SalePrice)
plot(train_data$FullBath + train_data$HalfBath , train_data$SalePrice)
plot(train_data$OverallQual, train_data$SalePrice)

```
# Data Exploration
```{r}
head(train_data)
head(test_data)
head(india_data_1)
head(india_data_2)
head(king_county_data) 
head(sydney_data)
dim(train_data)
dim(test_data)
dim(india_data_1)
dim(india_data_2)
dim(king_county_data) 
dim(sydney_data)

# To ensure reproduceability
set.seed(42)

#--- Partion the Data in the Proportion of 70%-30% ---
ind <- sample(2,nrow(train_data),replace=TRUE,prob=c(0.7,0.3))

# Assign the 70% partition to training the model
data_Trn_og <- train_data[ind==1,]

# Assign the 30% partition to testing the model
data_Tst_og <- train_data[ind==2,]
# fix the prices
hist(data_Trn_og$SalePrice)
hist(data_Tst_og$SalePrice)

#--- Partion the Data in the Proportion of 70%-30% ---
ind <- sample(2,nrow(king_county_data),replace=TRUE,prob=c(0.7,0.3))
# Assign the 70% partition to training the model
data_Trn_kc <- king_county_data[ind==1,]
# Assign the 30% partition to testing the model
data_Tst_kc <- king_county_data[ind==2,]
# fix the variables
data_Trn_kc$SalePrice <- data_Trn_kc$price
data_Tst_kc$SalePrice <- data_Tst_kc$price
data_Trn_kc <- data_Trn_kc%>% select(-price)
data_Tst_kc <- data_Tst_kc%>% select(-price)
# fix the prices
hist(data_Trn_kc$SalePrice)
hist(data_Tst_kc$SalePrice)


#--- Partion the Data in the Proportion of 70%-30% ---
ind <- sample(2,nrow(sydney_data),replace=TRUE,prob=c(0.7,0.3))
# Assign the 70% partition to training the model
data_Trn_sy <- sydney_data[ind==1,]
# Assign the 30% partition to testing the model
data_Tst_sy <- sydney_data[ind==2,]
# fix the variables
data_Trn_sy$SalePrice <- data_Trn_sy$price
data_Tst_sy$SalePrice <- data_Tst_sy$price
data_Trn_sy <- data_Trn_sy%>% select(-price)
data_Tst_sy <- data_Tst_sy%>% select(-price)
data_Trn_sy <- data_Trn_sy%>% select(-street)
data_Tst_sy <- data_Tst_sy%>% select(-street)
# fix the prices
hist(data_Trn_sy$SalePrice)
hist(data_Tst_sy$SalePrice)

#--- Partion the Data in the Proportion of 70%-30% ---
ind <- sample(2,nrow(india_data_2),replace=TRUE,prob=c(0.7,0.3))
# Assign the 70% partition to training the model
data_Trn_id <- india_data_2[ind==1,]
# Assign the 30% partition to testing the model
data_Tst_id <- india_data_2[ind==2,]
# fix the variables
data_Trn_id$SalePrice <- data_Trn_id$TARGET.PRICE_IN_LACS.
data_Tst_id$SalePrice <- data_Tst_id$TARGET.PRICE_IN_LACS.
data_Trn_id <- data_Trn_id %>% select(-TARGET.PRICE_IN_LACS.)
data_Tst_id <- data_Tst_id %>% select(-TARGET.PRICE_IN_LACS.)
data_Trn_id <- data_Trn_id %>% select(-ADDRESS)
data_Tst_id <- data_Tst_id %>% select(-ADDRESS)
# fix the prices
hist(data_Trn_id$SalePrice )
hist(data_Tst_id$SalePrice)


data_Trn <- data_Trn_og
data_Tst <- data_Tst_og

#data_Tst_sy
```

## Create gbm Model
```{r}
# Validation_Vars = list (SalePrice)
gbm_model <- gbm(formula=SalePrice ~., 
                 data=data_Trn, 
                 distribution = 'gaussian', 
                 n.trees = 50,
                 interaction.depth = 5,
                 n.minobsinnode = 30,
                 bag.fraction = 0.5,
                 shrinkage = 0.2,
                 cv.fold = 2,
                 n.cores=NULL )
```
# Create rf Model
```{r - Develop random forest Model}
rf_model = ranger(SalePrice ~ ., 
                  data=data_Trn, 
                  num.trees = 100,  
                  mtry=4, 
                  importance='permutation')



```

# Create glm Model
```{r Develop glm Model }
# Validation_Vars = list (loan_status, annRet, actualTerm, actualReturn)
glm_model <- cv.glmnet(data.matrix(data_Trn %>% select(-SalePrice)),
                       data_Trn$SalePrice, 
                       relax = TRUE, 
                       family = "gaussian")

```

```{r - mixed models}
bestIter<-gbm.perf(gbm_model, method='cv')
gbm_trn_predictions <- predict(gbm_model, newdata=data_Trn, n.tree= bestIter, type="response")
rf_trn_predictions <- predict(rf_model, data_Trn)$predictions
glm_trn_predictions <- predict(glm_model, data.matrix(data_Trn %>% select(-SalePrice)), type="response")[,1]

gbm_tst_predictions <- predict(gbm_model, newdata=data_Tst, n.tree= bestIter, type="response")
rf_tst_predictions <- predict(rf_model, data_Tst)$predictions
glm_tst_predictions <- predict(glm_model, data.matrix(data_Tst %>% select(-SalePrice)), type="response")[,1]

summary.gbm(gbm_model)
importance(rf_model)
coef(glm_model, s = "lambda.min")


#head(gbm_predictions)
#head(rf_predictions)
#head(glm_predictions)
#head(data_Trn$SalePrice)
#head(data_Trn$SalePricebin)
```

## Metrics
```{r - mixed models metrics}

max_num_bins = 10
for (n in 2:max_num_bins )
{
  num_bins = n
  data_Tst <- data_Tst %>% mutate(SalePricebin=ntile(SalePrice,num_bins))
  data_Trn <- data_Trn %>% mutate(SalePricebin=ntile(SalePrice,num_bins))

  #data_Trn$SalePricebin
  combineTrainingData <- data.frame(gbm_pred = gbm_trn_predictions, 
                                   rf_pred = rf_trn_predictions,
                                   glm_pred = glm_trn_predictions,
                                   bin = data_Trn$SalePricebin)

  combineTestData <- data.frame(gbm_pred = gbm_tst_predictions, 
                              rf_pred = rf_tst_predictions,
                              glm_pred = glm_tst_predictions,
                              bin = data_Tst$SalePricebin)


  #head(combineTrainingData)
  #head(combineTestData)
  
  mix_model_classifier = rpart(bin ~ ., data=combineTrainingData, method="class")
  tst_predictions <- predict(mix_model_classifier, newdata=combineTestData, type='class')


  #final_predictions <- predict(mix_model_classifier, newdata=combineTestData, type="response") %>% round(digits = 0)

  ref <- data.frame(gbm_pred = gbm_tst_predictions, 
                  rf_pred = rf_tst_predictions,
                  glm_pred = glm_tst_predictions,
                  price = data_Tst$SalePrice,
                  bin = data_Tst$SalePricebin,
                  pred = tst_predictions)
  
  head(ref)

  print(table(actual = ref$bin, predicted =ref$pred))
  #length(ref$bin)
  #sum(ref$bin == ref$pred)
  #print(num_bins)
  #print(sum(ref$bin == ref$pred)/length(ref$bin))
}


```












